### PR TITLE
[Preview] Support hmac validation

### PR DESCRIPTION
**Pull request by adinapoli**
Hey @tomtitchener !

As promised I have polished your PR, removing the need for `undefined` and adding your as a `CONTRIBUTOR`.

I have then written a test to mimic your initial bug report (namely having a Swift-encrypted string and wanting to decrypt it with Haskell), but the test fails on the HMAC step so I thought the most pragmatic thing to do was to open this PR (which includes _yours_ and _mine_ changes) for you to look at.

The test itself fails with this exception (which I have added):

screen shot 2016-08-21 at 15 36 07

But the data is decrypted successfully (I have removed the HMAC validation step and re-run the test temporarily, and the encrypted test was indeed `01`). Any idea what's going on?

### CODE REVIEW

**Comment by tomtitchener** [comment]
@adinapoli Nice job cleaning up the type annotations.  You're a master of type-fu!  The test fails because those encrypted bytes from my original PR are from the old rncryptor-hs, not from Swift.  My goal in that message was just to double-check the base64 decoding on Swift yielded the same stream of binary bytes as the base64 decoding on Haskell, i.e. that the Swift and Haskell APIs were decoding *exactly* the same byte streams, both for password and cipher text.  Sorry if that wasn't clear in my original post.  To verify the encrypted output from Haskell can be successfully decrypted in Swift, I've been manually testing by piping output from rncryptor-encrypt through base64, then pasting the output into a trivial Swift app, e.g.:

```
bash-3.2$  echo -n 01 | rncryptor-encrypt password | base64 -w 0
AwHDwUPu1R7EGGwvHjypxYPg4darNt+tNh4rZnpmD66Xp/BB42snR66ZPOUHES+Yw/1pexcQP7as15MKnG87Sy/7CPSm0B/OVyXhtAf6QZ1z8g==
```

Then ...

```
//
//  main.swift
//
import Foundation

let password = "password"

let pwdData = password.dataUsingEncoding(NSUTF8StringEncoding)

let base64String:String = "AwHDwUPu1R7EGGwvHjypxYPg4darNt+tNh4rZnpmD66Xp/BB42snR66ZPOUHES+Yw/1pexcQP7as15MKnG87Sy/7CPSm0B/OVyXhtAf6QZ1z8g=="

let decodedData:NSData = NSData(base64EncodedString: base64String, options:NSDataBase64DecodingOptions(rawValue: 0))!

// Decryption
do {
    let originalData = try RNCryptor.decryptData(decodedData, password: password)
    let originalString = String(data: originalData, encoding: NSUTF8StringEncoding)
    print(originalString)
    // ...
}
catch let error as NSError{
    print(error.localizedDescription)
}

```

Then, when I run:

```
Optional("01")
Program ended with exit code: 0

```

**Comment by adinapoli** [comment]
Hey @tomtitchener ,

thanks for clarifying! What I was testing in this case though was the other way around, namely that something _encrypted_ with Swift can be _decrypted_ with Haskell. As I do not have the Swift toolchain configured here, would you be able to give me a <cipherText,pwd> combo as produced by Swift, so that I can check that the HMAC validation is working?

If that's the case, I will add the test _testing the other way around_ (basically what you are describing in your latest comment) and that should give us the minimum degree of confidence this thing is gonna fly!

What do you think? Am I making sense? Thank you!

**Comment by tomtitchener** [comment]
@adinapoli Excellent point.  I've just been doing samples of the Haskell encrypt/Swift decrypt path.  Here are some snippets to show the Swift encrypt/Swift & Haskell decrypt path.  Doesn't work without a round-trip!

Here's the base64 encoding of swift encrypted string:

`AwHt9XBkvmyV9uLMfr+8Kh1b9ycYaStkIJVydQLH9hWlM9znw0Z/OuQ9ZLZgZiOfKOONZqpDU/GLN8dGvmszg9jx/4KH8SU5pt9M8wca9JqFnuqZCB3dBBKxumPhE8K07RD7ff6SYA1ryzXbgAHC3io7V8xvfKCXWtMoLYKv6bv0Yw==
`

Here's Swift example "code" (hacking) showing generation of string above:

```
let stringData = "Write the correct Spanish term for this greeting.\n\nHello.\n\n____".dataUsingEncoding(NSUTF8StringEncoding);
let encryptedData = RNCryptor.encryptData(stringData!, password: password);
let base64EncryptedData = encryptedData.base64EncodedStringWithOptions(NSDataBase64EncodingOptions(rawValue: 0))
print(base64EncryptedData);

// Decryption
do {
    let originalData = try RNCryptor.decryptData(encryptedData, password: password)
    let originalString = String(data: originalData, encoding: NSUTF8StringEncoding)
    print(originalString)
    // ...
}
catch let error as NSError{
    print(error.localizedDescription)
}
```

Here's XCode execution of Swift code with output of base64 encoded Swift encrypted output, plus double-check for Swift decryption:

```
AwHt9XBkvmyV9uLMfr+8Kh1b9ycYaStkIJVydQLH9hWlM9znw0Z/OuQ9ZLZgZiOfKOONZqpDU/GLN8dGvmszg9jx/4KH8SU5pt9M8wca9JqFnuqZCB3dBBKxumPhE8K07RD7ff6SYA1ryzXbgAHC3io7V8xvfKCXWtMoLYKv6bv0Yw==
Optional("Write the correct Spanish term for this greeting.\n\nHello.\n\n____")
Program ended with exit code: 0

```

Here's Haskell execution of the same decode (with newlines rendered):

```
bash-3.2$ echo -n AwHt9XBkvmyV9uLMfr+8Kh1b9ycYaStkIJVydQLH9hWlM9znw0Z/OuQ9ZLZgZiOfKOONZqpDU/GLN8dGvmszg9jx/4KH8SU5pt9M8wca9JqFnuqZCB3dBBKxumPhE8K07RD7ff6SYA1ryzXbgAHC3io7V8xvfKCXWtMoLYKv6bv0Yw== | base64 -d | rncryptor-decrypt HFZf1jwZeeOp4cS0T7WUKJlAHCqlJo9Q8vLQPeYYDGc=
Write the correct Spanish term for this greeting.

Hello.

____

```

**Comment by tomtitchener** [comment]
@adinapoli Ugh, I can see from a closer reading of Tests.hs that what you really want is that same example with the proper Swift encryption.  Working on it ...

**Comment by tomtitchener** [comment]
@adinapoli Here's a diff listing for Tests.hs that works, using output from Swift encrypt.

```
diff --git a/test/Tests.hs b/test/Tests.hs
index ea8b562..b7734ee 100644
--- a/test/Tests.hs
+++ b/test/Tests.hs
@@ -28,12 +28,12 @@ testEncryptDecryptRoundtrip =
 -- See: https://github.com/RNCryptor/rncryptor-hs/issues/11
 testForeignEncryption :: Assertion
 testForeignEncryption = do
-  let swiftEncrypted = B.pack [ 3,1,87,71,124,209,185,241,167,159,231,166,42,86
-                              , 249,135,241,131,72,179,174,66,55,129,9,123,87
-                              , 132,142,56,254,209,105,85,80,12,215,80,221,155
-                              , 233,226,46,42,150,167,34,17,77,156,74,75,88,239
-                              , 240,196,40,32,213,67,60,223,189,56,94,123,69,93
-                              , 247,161,244,207,21,51,231,90,88,198,109,111,174,204
-                              ]
+  let swiftEncrypted = B.pack [3,1,79,179,121,154,223,37,248,95,96,196,
+                               77,127,26,146,150,193,56,159,119,105,170,
+                               94,152,113,222,244,244,178,4,107,58,50,174,
+                               90,65,21,239,127,70,137,226,152,215,144,171,
+                               28,45,176,19,56,244,99,70,23,56,2,26,95,138,
+                               200,203,85,110,126,200,12,93,140,140,241,0,
+                               179,206,223,169,158,86,9,155,172]
   let swiftPassword = B.pack [112,97,115,115,119,111,114,100]
   decrypt swiftEncrypted swiftPassword @=? "01"
```

Here's the Swift code, FWIW:

```
let password       = "password";
let clearText      = "01".dataUsingEncoding(NSUTF8StringEncoding)
let cipherText     = RNCryptor.encryptData(clearText!, password: password)
let cipherArrayCnt = cipherText.length / sizeof(UInt8)
var cipherArray    = [UInt8](count: cipherArrayCnt, repeatedValue: 0)
cipherText.getBytes(&cipherArray, length: cipherArrayCnt)
print(cipherArray)

```

**Comment by adinapoli** [comment]
Great, thanks Tom! Will try to incorporate everything tomorrow ;)

**Comment by adinapoli** [comment]
All done, thanks @tomtitchener !

I'm going to go on and merge this. Travis is complaining about some failures for GHC 7.10.3, but they are hardly relevant and we should really port Travis to use `stack` rather then cabal for building, but that's outside the scope of this PR.

What's still left (but can be addressed in separate tickets) is:

* More test coverage (_especially_ the streaming API)
* Test vectors

**Pull request merged**
